app1/urls.py
#url of app1
#from django.contrib import admin
from django.urls import path
from . import views

app_name = 'app1'
urlpatterns = [
	path('', views.home, name='home'),
	path('topics/', views.topics, name = 'topics'),
	path('topics/<int:topic_id>/', views.topic, name = 'topic'),
	path('add_topic/', views.add_topic, name= 'add_topic'),#to display the form we just created
	path('add_entry/<int:topic_id>/', views.add_entry, name = 'add_entry'),
	path('edit_entry/<int:entry_id>/', views.edit_entry, name  = 'edit_entry'),


    
]

learning_journal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('app1', include('app1.urls' )),#app1 is url here
    path('', include('app1.urls' )),
]

app1/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	text = models.CharField(max_length = 200)
	date_added  = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.text

class Entry(models.Model):
	#topic = models.ForeignKey(Topic)# till DJANGO 1.9
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE )
	text  =  models.TextField()
	date_added = models.DateTimeField(auto_now_add = True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		if len(self.text) >75:
			return self.text[:75] + '...'
		return self.text[:75]

app1/forms.py
from django import forms
from .models import Topic, Entry
class TitleForm (forms.ModelForm):#1st form

	class Meta:
		model = Topic#built the form from topic model
		fields = ['text']#include in form only fields
		labels = {'text': ''}#not generate label for text fields

class ContentForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': 'Your Content:'}
		widgets = {'text': forms.Textarea(attrs = {'cols': 80})}


		

app1/views.py
'''
Views are Python functions that receive an HttpRequest object 
and returns an HttpResponse object. 

Receive a request as a parameter and returns a response as a result. 
'''

from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TitleForm, ContentForm
# Create your views here.
def home(request):
	return render(request, 'app1/home.html')

def topics(request):
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}
	return render(request, 'app1/topics.html', context)

def topic(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'app1/topic.html', context)

def add_topic(request):
	if request.method != 'POST':
		form = TitleForm()
	else:
		#if post data submitted
		form = TitleForm(data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('app1:topics')

	context= {'form': form}
	return render(request, 'app1/add_topic.html', context)
	
def add_entry(request, topic_id):
	topic = Topic.objects.get(id = topic_id)

	if request.method != 'POST':
		form = ContentForm()

	else:
		form = ContentForm(data = request.POST)
		if form.is_valid():
			add_entry = form.save(commit = False)
			add_entry.topic = topic
			add_entry.save()
			return redirect('app1:topic', topic_id = topic_id)
	
	context = {'topic': topic, 'form': form}
	return render(request, 'app1/add_entry.html', context)


def edit_entry(request, entry_id):
	entry = Entry.objects.get(id =entry_id)
	topic = entry.topic

	if request.method != 'POST':
		form = ContentForm(instance = entry)
	else:
		form = ContentForm(instance=entry, data=request.POST)
		if form.is_valid:
			form.save()
			return redirect('app1:topic', topic_id = topic.id)
	context  = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'app1/edit_entry.html', context)

app1/templates/app1/add_entry.html
{% extends 'app1/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title> {{ topic }} </title>
</head>
<body>
	<p> <a href="{% url 'app1:topic' topic.id %}"> {{ topic }}</a></p>
	<p>Add a new entry:</p>
	<form action="{% url 'app1:add_entry' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit"> Add entry </button>
	</form>
		

</body>
</html>
{% endblock content %}

app1/templates/app1/add_topic.html
{% extends 'app1/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Whiteboard</title>
</head>
<body>
	<p>Add a new topic:</p>
	<form action="{% url 'app1:add_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit"> Add topic </button>
	</form>
		

</body>
</html>
{% endblock content %}

app1/templates/app1/base.html
<a href = "{% url 'app1:home'  %}"> Home</a> 
<p>	</p>
<a href="{% url 'app1:topics' %}">Topics</a>

{% block content %}{% endblock content %}

app1/templates/app1/edit_entry.html
{% extends 'app1/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title> {{ topic }}  </title>
</head>
<body>
	<p> <a href="{% url 'app1:topic' topic.id %}"> {{ topic }}</a></p>
	<p>Edit entry:</p>
	<form action="{% url 'app1:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit"> Save changes </button>
	</form>
		

</body>
</html>
{% endblock content %}

app1/templates/app1/home.html
{% extends "app1/base.html" %}
{% block content %}
	<!DOCTYPE html>
	<html>
	<head>
		<title>Whiteboard</title>
	</head>
	<body>
		
	 	<p>This website is a journal which we use to manage details of different topic we learn so far...  </p>

	</body>
	</html>
{% endblock content %}

app1/templates/app1/topic.html
{% extends "app1/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title> {{topic}}</title>
</head>
<body>
	
	<p>Topic: {{topic}}</p>
		<a href="{% url 'app1:add_entry' topic.id %}"> Add new entry</a> 

	<p>Entries:</p>
	<p>
	<ul>
	{% for entry in entries %}
		<li>
			{{entry.date_added|date:'M d, Y H:i'}}
			{{ entry.text|linebreaks}}
			<p>
				<a href="{% url 'app1:edit_entry' entry.id %}"> Edit Entry</a>
			</p>
		</li>
	{% empty %}
		<li>
			No Entries Yet.
		</li>
	{% endfor %}
	</ul>

</body>
</html>
{% endblock content %}

app1/templates/app1/topics.html
{% extends "app1/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Whiteboard</title>
</head>
<body>
	
	<p>Topics Created</p>
	<ul>
		{% for topic in topics %}
			<li>
			<a href="{% url 'app1:topic' topic.id %}">{{ topic }}</a>
			</li>
		{% empty %}
			<li> No topics yet.</li>
		{% endfor %}
	</ul>
	<a href="{% url 'app1:add_topic' %}">Add Topic </a>

</body>
</html>

{% endblock content %}
	